export type UseCase = {
  id: string;
  title: string;
  who: string;
  trigger: string;
  steps?: string[];
  before?: string;
  after?: string;
};

export type ProjectDoc = {
  // 1. Problem Statement — why this project exists
  problemStatement?: string;
  // 2. Existing Problems — bullet list of pain points
  existingProblems?: string[];
  // 3. Why This Project — motivation / differentiation
  whyThisProject?: string;
  // 4. Objectives — goals of the project
  objectives?: string[];
  // 5. Solution — how it solves the problem
  solution?: string;
  // 6. Complete Features (detailed)
  features?: string[];
  // 7. User Roles
  userRoles?: { role: string; description: string }[];
  // 8. Use Cases
  useCases?: UseCase[];
  // 9. Workflow — step-by-step flow
  workflow?: string[];
  // 10. Business Flow — business logic / process
  businessFlow?: string[];
  // 11. Before vs After
  beforeVsAfter?: { aspect: string; before: string; after: string }[];
  // 12. Screenshots — image URLs
  screenshots?: { url: string; caption?: string }[];
  // 13. Future Scope
  futureScope?: string[];
  // 14. Limitations
  limitations?: string[];
  // 15. Conclusion
  conclusion?: string;
};

export type Project = {
  slug: string;
  name: string;
  status: "active" | "shipped" | "beta" | "archived";
  oneLiner: string;
  problem: string;
  stack: string[];
  metrics: { label: string; value: string }[];
  github?: string;
  liveUrl?: string;
  pdfUrl?: string;
  videoUrl?: string;
  heroImage?: string;
  gallery?: string[];
  featured: boolean;
  docs?: ProjectDoc;
};

export const projects: Project[] = [
  {
    slug: "railmind",
    name: "RailMind",
    status: "beta",
    oneLiner: "AI-Powered Cognitive Maintenance Platform for Railway Infrastructure — signal risk, asset health, and maintenance ops unified in one system.",
    problem: "Railway infrastructure teams operate on siloed, reactive tooling — asset state, signal risk, and maintenance history live in disconnected systems, so failures get diagnosed after the fact instead of predicted before it.",
    stack: ["Next.js 14", "NestJS 10", "LangGraph", "PostgreSQL", "Neo4j", "Qdrant", "Redis", "Turborepo", "GPT-4o-mini", "Mapbox GL", "Prisma", "WebSockets"],
    metrics: [
      { label: "Production readiness", value: "9.7 / 10" },
      { label: "API routes audited", value: "58" },
      { label: "Files in final build", value: "232" },
      { label: "Audit phases", value: "6" },
    ],
    github: "https://github.com/Ambivert01/RAIL-MIND",
    liveUrl: "https://railmind-web.onrender.com",
    pdfUrl: "/RailMind/RailMind.pdf",
    featured: true,
    docs: {
      problemStatement:
        "Indian Railways operates 68,000+ km of track, 6,000+ stations, and 12,000+ signalling systems. Signal failures are the #1 cause of operational disruption — contributing to 23% of all train delays. On busy corridors, a signal failure occurs every 72 hours, triggering cascading delays affecting 15–40 trains. Despite the scale, maintenance is entirely reactive: engineers respond only after failures occur. A typical investigation takes 4–8 hours — manual log searches, paper SOPs, phone calls to senior engineers — and the same failure returns months later because root causes are never captured and lessons are never stored.",
      existingProblems: [
        "Tribal Knowledge Loss: 3 senior engineers hold the entire failure history of a zone. When they retire, 20+ years of pattern knowledge leaves with them — estimated ₹2–5 crore institutional loss per departure.",
        "No Pattern Detection: A signal fails 5 times for the identical systemic reason across different shifts. Nobody connects the dots because there is no system that does.",
        "Reactive Maintenance: Assets are fixed after failure, not before. Emergency repairs cost 3–5× more than scheduled maintenance.",
        "Siloed Data: Incidents in SCADA, maintenance history in Excel, procedures in paper binders, live context in WhatsApp groups — completely disconnected.",
        "No Risk Propagation: When Signal S11 fails due to a batch component defect, nearby identical assets are never flagged for inspection.",
        "Investigation Bottleneck: Resolution time depends entirely on which engineer is on call and what they personally remember.",
        "No Semantic Search: 'Moisture infiltration' and 'water ingress' are the same problem — but keyword-based systems treat them as unrelated.",
      ],
      whyThisProject:
        "Every existing tool solves one piece of the problem in isolation — SCADA gives real-time alerts but no history, CMMS logs work orders but detects no patterns, spreadsheets store data but make it unsearchable. No system synthesizes all three layers simultaneously. RailMind was built to be that unified cognitive layer: combining transactional precision (PostgreSQL), topological relationship mapping (Neo4j), and semantic meaning search (Qdrant) — orchestrated by a 7-agent LangGraph pipeline that delivers a complete, explainable engineering recommendation in under 60 seconds.",
      objectives: [
        "Replace 4–8 hour manual investigations with a 60-second AI pipeline.",
        "Eliminate tribal knowledge loss by automatically capturing every resolved incident as institutional memory.",
        "Enable predictive maintenance by detecting failure patterns before assets degrade.",
        "Propagate risk across connected assets when a failure is detected.",
        "Provide explainable, auditable AI recommendations — not black-box outputs.",
        "Support 6 user roles with strict server-side access control.",
        "Build a system that scales from a 50-asset pilot to 12,000+ national signals without architectural changes.",
      ],
      solution:
        "RailMind deploys three specialized data stores coordinated by a multi-agent orchestration layer. When a signal anomaly is detected, a 7-agent LangGraph pipeline executes in 60 seconds: the Incident Agent searches 100+ historical records semantically, the Knowledge Agent extracts relevant SOPs from vector memory, the Risk Agent computes a 5-factor risk score and propagates risk to adjacent assets via Neo4j graph traversal, the Engineer Agent maps root causes to corrective actions, the Planner Agent auto-generates a work order if risk exceeds threshold, and the Learning Agent vectorizes the resolution for future reference. The Decision Service synthesizes all outputs into a 7-layer explainable recommendation with a full audit trail.",
      features: [
        "Digital Twin Map — Mapbox GL viewport with 50 assets, dynamic risk coloration (GREEN→YELLOW→ORANGE→RED), layer toggles, 30s live polling, graceful offline fallback to grid layout.",
        "Asset Intelligence Profile — 5-tab deep-dive: Overview (health, risk score, install date), Incidents (full chronological log), Maintenance (work order history), Recommendations (approve/reject/complete), Graph (topological neighbors).",
        "Knowledge Graph Explorer — ReactFlow interface, dynamic node expansion, deterministic jitter-free layout, quick-load focal points (S11, INC-044, Rivergate Station), air-gapped 9-node demo fallback.",
        "Risk Intelligence Center — Network KPI cards, 50-asset heatmap grid, 7-day historical escalation chart, 30-day predictive forecast, parallel batch recalculation engine (10 assets/batch).",
        "Topological Risk Propagation — Neo4j PART_OF traversal: +20 risk to immediate neighbors, +12 to secondary, +6 to tertiary when an asset degrades.",
        "Incident Management System — Full lifecycle (OPEN→INVESTIGATING→RESOLVED→ARCHIVED), agent thought timeline, clustering engine for similar incidents, automated learning hooks on close.",
        "Memory Search (Semantic Hybrid RAG) — Unified queries across 6 Qdrant collections, graph-enriched retrieval, mock embedding fallback with visible warning banner.",
        "Recommendations Engine — Auto-generated by pipeline, strict state machine (PENDING→APPROVED→IN_PROGRESS→COMPLETED/REJECTED), confirmation modals for destructive actions.",
        "Maintenance Planner — Risk-prioritized queue, 7 work order types enforced, auto-provisioning when risk score ≥ 31 (CRITICAL = same-day, HIGH = 7-day deadline).",
        "Real-Time WebSocket Broadcasts — Sub-second push notifications to all connected clients on incident create/update/close.",
        "7-Layer Decision Service — Evidence scoring (0–100), context synthesis, primary recommendation selection, priority determination, confidence formula C = (0.45·E) + (0.30·K) + (0.25·R), conflict resolution, 6-step explainability chain.",
        "Role-Based Access Control — 6 roles (ADMINISTRATOR, ENGINEER, MAINTENANCE_MANAGER, SAFETY_OFFICER, OPERATOR, TRAINING_OFFICER), JWT + RolesGuard enforced server-side on every route.",
        "Redis Cache Layer — 60-second TTL on all agent pipeline responses, instant cache-hit returns.",
        "Full Audit Trail — Every AI decision logged with agent run trace, confidence inputs, source citations, and approving user identity.",
      ],
      userRoles: [
        { role: "ADMINISTRATOR", description: "Absolute access to all data. Execute raw Neo4j Cypher queries, modify user accounts, adjust agent models, full incident and work order override capability." },
        { role: "ENGINEER", description: "Full data access. Create, modify, and close incidents. Generate work orders, approve AI recommendations, trigger LangGraph pipelines, request memory re-indexing." },
        { role: "MAINTENANCE_MANAGER", description: "Full data access. Read-only on incidents. Full creation, modification, and bulk approval of work orders. Adjust technician assignments and cost variables." },
        { role: "SAFETY_OFFICER", description: "Full data access. Read-only on incidents and maintenance queues. Force zone-wide risk recalculations and export compliance logs." },
        { role: "OPERATOR", description: "Full data access. Create new incident tickets (read-only elsewhere). Submit queries and view network map updates." },
        { role: "TRAINING_OFFICER", description: "Full data access. Read-only on incidents and maintenance. Manage training documentation inputs and extract lesson histories." },
      ],
      useCases: [
        {
          id: "UC-01",
          title: "Signal Failure Investigation",
          who: "Depot Field Engineer / Control Room Operator",
          trigger: "Operational telemetry registers an intermittent signal drop on Signal S11.",
          steps: [
            "User loads Signal S11 Asset Intelligence Profile and clicks 'Ask RailMind'.",
            "LangGraph pipeline executes — Incident Agent finds 5 related historical tickets over 18 months.",
            "Risk Agent flags 87/100 CRITICAL score, correlates with wet weather windows.",
            "Knowledge Agent extracts SOP-007 (Relay Replacement Procedure).",
            "Engineer Agent outputs action plan: replace relay assembly, inspect housing seal.",
            "Planner Agent auto-generates work order with same-day deadline.",
            "Learning Agent vectorizes investigation for future reference.",
          ],
          before: "4–8 hours manual log search, phone calls, paper SOPs.",
          after: "60-second automated diagnostic with full citation trail.",
        },
        {
          id: "UC-02",
          title: "Pre-Monsoon Risk Assessment",
          who: "Safety Officer / Maintenance Director",
          trigger: "Preparing infrastructure ahead of seasonal monsoon weather.",
          steps: [
            "Safety Officer opens Risk Intelligence Center heatmap.",
            "Filters network by HIGH and CRITICAL — 8 vulnerable assets highlighted.",
            "System shows statistical correlation with historical rain-driven water ingress events.",
            "Officer bulk-approves preventive inspection entries.",
            "Planner Agent auto-outputs 8 scheduled work orders with 30-day deadline.",
          ],
          before: "Reactive — failures discovered during monsoon season.",
          after: "Predictive — 8 assets inspected and secured before season starts.",
        },
        {
          id: "UC-03",
          title: "Systemic Root Cause Pattern Discovery",
          who: "Senior Signal Engineer",
          trigger: "Monthly infrastructure performance audit.",
          steps: [
            "Engineer queries Knowledge Graph Explorer for 'relay corrosion'.",
            "Neo4j reveals cluster of 12 incidents across 8 signaling points.",
            "All affected assets share age >10 years and coastal location.",
            "Engineer creates inspection rule for all coastal relays >10 years old.",
            "System auto-recalculates and raises risk priority of 15 additional assets.",
          ],
          before: "No system connects dots across incidents from different shifts.",
          after: "Network-wide intelligence from isolated incident entries.",
        },
        {
          id: "UC-04",
          title: "Junior Engineer Onboarding",
          who: "Newly Assigned Trainee Field Technician",
          trigger: "Assigned to unfamiliar sector with legacy infrastructure.",
          steps: [
            "New hire opens Asset Intelligence Profile for Signal S22.",
            "System surfaces 2 years of local faults, component overrides, regional failure modes.",
            "Technician queries Memory Search: 'coastal relay breakdown procedures'.",
            "Receives 8 structured lessons learned + links to current maintenance specs.",
          ],
          before: "6-month field shadowing dependent on senior engineer availability.",
          after: "Day 1 access to complete institutional knowledge base.",
        },
        {
          id: "UC-05",
          title: "Incident Triage During Severe Disruption",
          who: "Control Room Supervisor",
          trigger: "Lightning storm knocks out 3 primary signaling installations simultaneously.",
          steps: [
            "Dashboard flashes 3 open CRITICAL incident tickets instantly.",
            "Risk Heatmap flags 12 adjacent assets orange via topological propagation.",
            "Supervisor uses pipeline's prioritized breakdown to route repair crews.",
            "Pre-generated work orders dispatched to highest cascade-risk assets first.",
          ],
          before: "Sub-optimal resource allocation under crisis pressure.",
          after: "Data-driven crew routing in seconds during high-pressure emergencies.",
        },
        {
          id: "UC-06",
          title: "Post-Incident Automated Knowledge Capture",
          who: "System (Automated) / Closing Field Technician",
          trigger: "Ticket status changed from INVESTIGATING to RESOLVED.",
          steps: [
            "Technician enters resolution steps and root cause (contact corrosion).",
            "LearningAgent.onIncidentClosed() fires automatically.",
            "Text converted to vector embeddings, saved to Qdrant lessons collection.",
            "PostgreSQL LessonLearned row created. Audit registry entry logged.",
          ],
          before: "Lessons lost in email threads and WhatsApp groups within weeks.",
          after: "Zero knowledge loss — every resolution becomes searchable institutional memory.",
        },
        {
          id: "UC-07",
          title: "Fleet-Wide Risk Propagation",
          who: "Automated Risk Engine",
          trigger: "Asset risk score crosses into CRITICAL zone.",
          steps: [
            "Risk Agent traverses Neo4j PART_OF and CONNECTED_TO paths.",
            "Locates S12 and S13 in same physical interlocking house, same batch code.",
            "Applies +20 risk bump to both units automatically.",
            "Browser alerts and email flags dispatched to safety dispatchers.",
          ],
          before: "Adjacent assets never inspected after a related failure.",
          after: "Cascade vulnerability detection without manual engineering review.",
        },
        {
          id: "UC-08",
          title: "Regulatory Compliance Auditing",
          who: "Railway Safety Board Inspector / Regional Audit Team",
          trigger: "Annual statutory safety verification or post-incident regulatory review.",
          steps: [
            "Safety Officer opens Audit Logs panel, filters by Incident resource over 12 months.",
            "System exports complete unmodifiable decision trace for every AI investigation.",
            "Each record lists confidence inputs, vector-matched source documents, and approving user identities.",
          ],
          before: "Gut-feel risk assessment with no verifiable documentation trail.",
          after: "Explainable, auditable records that fully meet Railway Safety Board standards.",
        },
      ],
      workflow: [
        "Signal anomaly detected via telemetry or operator input.",
        "AgentsService checks Redis cache (60s TTL) — cache hit returns instantly.",
        "Cache miss: ExecutiveAgent instantiates LangGraph state machine.",
        "load_asset — fetches telemetry and metadata from PostgreSQL.",
        "incident_agent — hybrid PostgreSQL + Qdrant semantic search across historical tickets.",
        "knowledge_agent — extracts SOP paragraphs from Qdrant, appends Neo4j structural context.",
        "risk_agent — computes 5-factor risk score, traverses Neo4j graph, propagates risk to neighbors.",
        "engineer_agent — maps root causes to specific corrective actions from validated SOPs.",
        "planner_agent — auto-provisions work order if risk score ≥ 31.",
        "learning_agent — packages resolution context for vector storage.",
        "DecisionService executes 7-layer synthesis: evidence scoring → context merge → recommendation selection → priority → confidence formula → conflict resolution → explainability chain.",
        "GPT-4o-mini generates structured natural language response with citations and work order.",
        "Response cached in Redis. WebSocket broadcasts workflow:completed to all clients.",
      ],
      businessFlow: [
        "Asset degrades or anomaly detected → Incident ticket auto-created or operator-logged.",
        "AI pipeline investigates → Risk score computed, pattern matched, SOP retrieved.",
        "Recommendation generated → Engineer reviews, approves, or rejects via dashboard.",
        "Work order created → Maintenance team assigned, deadline set by urgency level.",
        "Field technician executes repair → Resolution logged with root cause.",
        "Incident closed → LearningAgent vectorizes resolution into institutional memory.",
        "Next similar failure → System finds this resolution in 60 seconds instead of 4–8 hours.",
        "Scale: 100 incidents = local correlations. 10,000 incidents = unmatchable knowledge repository.",
      ],
      beforeVsAfter: [
        { aspect: "Investigation Time", before: "4–8 hours (manual logs, phone calls, paper SOPs)", after: "Under 60 seconds (automated AI pipeline)" },
        { aspect: "Pattern Detection", before: "Manual, rarely achieved across shifts", after: "Automatic via graph-vector correlation" },
        { aspect: "Risk Assessment", before: "Subjective gut feel, localized", after: "5-factor deterministic formula + Neo4j propagation" },
        { aspect: "Lesson Capture", before: "Informal — lost in emails and WhatsApp", after: "Automated vectorization on every incident close" },
        { aspect: "New Engineer Onboarding", before: "6 months field shadowing", after: "Day 1 access to full historical memory" },
        { aspect: "Maintenance Model", before: "Strictly reactive (fix after failure)", after: "Fully predictive (ranked by failure probability)" },
        { aspect: "Cost Per Failure", before: "₹5L–₹48L direct + cascade costs", after: "Prevented: ₹0 | Mitigated: ₹1L–₹2L" },
        { aspect: "Compliance Audit", before: "No verifiable documentation trail", after: "7-layer explainable audit trail per investigation" },
      ],
      screenshots: [
        { url: "/RailMind/RailMind1.png", caption: "Dashboard Overview" },
        { url: "/RailMind/RailMind2.png", caption: "Asset Intelligence Profile" },
        { url: "/RailMind/RailMind3.png", caption: "Knowledge Graph Explorer" },
        { url: "/RailMind/RailMind4.png", caption: "Risk Intelligence Center" },
        { url: "/RailMind/RailMind5.png", caption: "Incident Management" },
        { url: "/RailMind/RailMind6.png", caption: "Memory Search" },
        { url: "/RailMind/RailMind7.png", caption: "Maintenance Planner" },
        { url: "/RailMind/RailMind8.png", caption: "Digital Twin Map" },
      ],
      futureScope: [
        "Parallel Agent Execution — run Incident and Knowledge agents simultaneously to cut pipeline time.",
        "Time Travel UI — step backward through network risk states during historical incidents.",
        "Mobile Engineering App — React Native app with offline sync for remote track sectors.",
        "Direct SCADA Pipeline Ingestion — auto-open incident tickets from live telemetry streams.",
        "Predictive Supply Procurement — auto-order parts 6 months ahead of predicted failures.",
        "Cross-Zone Pattern Sharing — failure playbooks from one zone auto-update all other zones.",
        "Advanced Management Console — full visual control over user accounts, roles, graph rules.",
        "Object Store Connectors — attach inspection photos and field manuals to tickets via MinIO.",
        "Self-hosted LLM — switch to on-premises Llama 3 for fully air-gapped deployments.",
        "National Scale — all 12,000+ signals, multi-zone knowledge sharing, Railway Safety Board compliance dashboard.",
      ],
      limitations: [
        "OpenAI API dependency — semantic search degrades to hash-similarity model if API key is unavailable (usingMockEmbeddings warning shown in UI).",
        "60-second pipeline timeout — complex multi-layer queries that exceed the window return a pre-formatted fallback response.",
        "Synthetic data — current 50-asset pilot uses generated engineering histories mirroring real faults; live SCADA ingestion requires external integration.",
        "No native SCADA connectors — legacy hardware integration requires external teams to configure REST/WebSocket ingestion endpoints.",
        "English-only semantic search — regional railway terminology is mapped, but native Hindi querying is on the roadmap.",
        "Single-region deployment — pilot is not multi-zone HA; national scale requires Kubernetes cluster upgrade.",
      ],
      conclusion:
        "RailMind is a unified cognitive intelligence layer that sits on top of existing infrastructure investments, transforming disconnected operational data into clear, actionable insights. Its compounding architecture means the system grows more valuable with every closed ticket: 100 incidents establishes local correlations, 10,000 incidents creates an unmatchable institutional knowledge repository accessible to any engineer on day one. By combining relational precision (PostgreSQL), topological graph modeling (Neo4j), and semantic vector matching (Qdrant) inside a reliable 7-agent LangGraph pipeline, RailMind eliminates fragmented human memory and black-box AI. For Indian Railways, this is a clear, verifiable path toward zero signal failures, optimized maintenance budgets, and permanent institutional knowledge retention across national infrastructure.",
    },
  },
  {
    slug: "pairspace",
    name: "PairSpace",
    status: "beta",
    oneLiner: "Digital intimacy infrastructure for distributed relationships — a private, two-person space built around the dyad, not the broadcast.",
    problem: "Most communication technology is built for broadcast or transaction. Neither maps onto the actual problem of sustaining one continuous relationship between two specific people over distance and time.",
    stack: ["React 18", "Vite 5", "Tailwind CSS", "Framer Motion", "Node.js 20", "Express 4", "Socket.IO", "MongoDB", "Mongoose", "JWT", "WebRTC", "node-cron", "Multer", "Sharp", "Jest"],
    metrics: [
      { label: "Features", value: "18" },
      { label: "Realtime namespaces", value: "6" },
      { label: "Tests", value: "124" },
      { label: "Theoretical frameworks", value: "8" },
    ],
    github: "https://github.com/Ambivert01/PAIR-SPACE",
    liveUrl: "https://pairspace-web.onrender.com/",
    pdfUrl: "/PairSpace/PairSpace.pdf",
    featured: true,
    docs: {
      problemStatement:
        "Most communication technology is built for one of two purposes: broadcast (one-to-many, optimized for reach) or transaction (task-to-completion, optimized for efficiency). Neither maps onto the actual problem of sustaining one continuous, asymmetric-in-stakes relationship between two specific people over distance and time. When two people used to share a room, an enormous amount of relational work happened automatically — a glance, a shared silence, noticing someone's bad day from their posture. Remove the room, and all of that work either has to be replaced by something else, or it simply stops happening. WhatsApp, Instagram, Zoom, and calendar tools all fail not because they're poorly engineered, but because they were built for a different unit — the individual, the audience, the call, the task — and a relationship is none of those things.",
      existingProblems: [
        "Temporal Asynchrony: Two people in different timezones have a shrinking window for live interaction. The coordination cost of finding that window is a real, recurring tax paid hundreds of times over the life of a relationship.",
        "Experiential Co-absence: Partners cannot share an experience simultaneously — a meal, a film, a walk. Remove simultaneity and you remove the raw material that 'remember when' stories are made from.",
        "Affective Opacity: A distant partner has almost no ambient information about how the other is actually feeling. A co-located partner gets this for free, dozens of times a day, through tone and posture.",
        "Ritual Erosion: Distance and tool fragmentation make small repeated gestures — a goodnight call, a Sunday routine — more effortful to start and therefore easier to quietly let lapse.",
        "Narrative Discontinuity: Without a shared repository, the 'story' of a relationship scatters across camera rolls, chat histories, and fading memory. Nobody assembles it into anything coherent.",
        "Context Collapse: On platforms where many audiences coexist, people flatten their self-presentation to suit the most conservative viewer — suppressing exactly the unguarded, vulnerable content close relationships are built on.",
        "No Reciprocity Enforcement: Disclosure that is asymmetric or forced tends to backfire. No existing tool encodes reciprocity at the protocol level — it relies entirely on goodwill.",
      ],
      whyThisProject:
        "PairSpace is built around a single, narrow unit of design: the dyad — exactly two people who have agreed to share a digital space. The underlying data model gives a relationship exactly two member fields, not a members array — meaning two-person exclusivity is a structural guarantee, not a policy. Every feature traces back to a specific, named structural deficit of distance and a specific theoretical mechanism for addressing it: Attachment Theory, Social Presence Theory, Social Penetration Theory, Context Collapse, Gottman's Rituals of Connection, Ambient Intimacy, Narrative Identity, and Equity Theory. The coherence across all features — not any single one — is what a general-purpose messaging app cannot structurally provide.",
      objectives: [
        "Eliminate context collapse by making the dyad the structural unit — no audience, no third member possible at the data model level.",
        "Address temporal asynchrony with a live Timezone Bridge showing dual clocks, awake/asleep heuristics, and a computed golden availability window.",
        "Restore experiential co-presence with join-gated synchronized Watch Together — playback disabled until both partners are present.",
        "Solve affective opacity with a Daily Mood Check-In (one emoji + note, daily reset) and a sub-conversational Heartbeat Tap.",
        "Scaffold relationship rituals with habit streaks and a Planner that remembers and maintains rhythm.",
        "Automate narrative curation with AI Story generation at meaningful milestones so couples don't have to assemble their own history.",
        "Encode reciprocal disclosure at the protocol level via Journal visibility rules — a partner's entry is literally unreadable until the other contributes in return.",
        "Preserve institutional memory of the relationship in a purpose-built Memory Timeline with PIN-locked individual entries.",
      ],
      solution:
        "PairSpace deploys a layered channel architecture — asynchronous chat (lean) → mood signal (emotionally targeted) → synchronized activity (rich, simultaneous) → live call (richest) — coordinated by a real-time WebSocket layer and a peer-to-peer WebRTC call stack. The Journal's visible_after_response rule encodes Social Penetration Theory directly as an access-control permission. The Heartbeat Tap uses a deliberate 30-second cooldown as a scarcity mechanic — a gesture sent without limit stops meaning 'I'm thinking of you' and starts meaning 'this button is satisfying to press.' Time Capsules support mutual-unlock conditions requiring both partners to actively confirm readiness, encoding the idea that some thresholds in a relationship should be crossed together, not unilaterally.",
      features: [
        "Private Chat — real-time messaging with reactions, replies, edit/delete, typing indicators, read receipts, media, and voice notes.",
        "Voice & Video Calls — WebRTC peer-to-peer with mute, camera toggle, screen share, auto-timeout, and call history.",
        "Memory Timeline — shared photo/video/milestone timeline with PIN locking, reactions, comments, and AI emotion tagging.",
        "Watch Together — synchronized video/audio with live position sync — partner joins at the exact right second.",
        "Thinking of You (Heartbeat Tap) — one-tap pulse that appears on partner's screen instantly, no words needed.",
        "Daily Mood — both partners share a daily emoji mood visible on each other's dashboard.",
        "Timezone Bridge — both local times, awake/sleeping status, golden overlap hours, and distance apart.",
        "Digital Gifts — surprise gifts with countdown timers (precise hours/minutes), reveal animations, and reaction mechanics.",
        "Time Capsules — lock messages and media until a future date, mutual unlock, or anniversary.",
        "Journal — shared journal with visibility rules: write for each other, or reveal only after they respond.",
        "Planner — habits with streak tracking, events, goals, recurring reminders, and relationship calendar.",
        "Games — 8 turn-based couple games: Truth or Dare, Word Association, Trivia, and more.",
        "AI Insights — weekly relationship pattern analysis: message frequency, emotional diversity, activity consistency.",
        "AI Story — milestone-triggered narrative stories: '100 messages together,' '1 year anniversary.'",
        "Smart Notifications — anniversary reminders with 1-day early heads-up, real-time delivery, scheduled system.",
        "Privacy Controls — PIN-lock memories, session management, data export, incognito mode.",
        "Personalization — custom themes, wallpapers, relationship name, font, and mood settings.",
        "Offline Sync — messages queued in IndexedDB, delivered automatically on reconnect with deduplication.",
      ],
      userRoles: [
        { role: "Partner A (Initiator)", description: "Sends the invite, sees pending state until accepted. Equal authority over all shared content — no 'owner' privileges." },
        { role: "Partner B (Joiner)", description: "Accepts invite to activate the space. Fully symmetrical permissions — neither partner holds admin power over the other's account or data." },
      ],
      useCases: [
        {
          id: "UC-01",
          title: "Timezone-Aware Communication",
          who: "Long-distance couple in different timezones",
          trigger: "One partner wants to reach out but doesn't know if the other is awake.",
          steps: [
            "Open Timezone Bridge — see both local times and awake/asleep heuristic at a glance.",
            "Check the computed golden window for likely mutual availability.",
            "Send a Heartbeat Tap if outside the window — zero-content, no obligation to reply.",
            "Schedule a call for the next golden window.",
          ],
          before: "Timezone arithmetic in your head, risk of waking the other person.",
          after: "One screen answers 'can I reach them now?' without any calculation.",
        },
        {
          id: "UC-02",
          title: "Synchronized Watch Together",
          who: "Couple separated by distance wanting to share a film",
          trigger: "Both partners free at the same time, want to watch something together.",
          steps: [
            "One partner starts a Watch Together session and shares the link/title.",
            "Playback controls are disabled until both are present — join-gated.",
            "Second partner joins; system asks active device for live position and hands it to joiner.",
            "Both watch in sync with drift correction above threshold only.",
          ],
          before: "'Press play on 3' over text — always slightly out of sync, no shared reactions.",
          after: "Genuine simultaneity — the same frame at the same moment.",
        },
        {
          id: "UC-03",
          title: "Reciprocal Journal Entry",
          who: "Partner wanting to share something vulnerable",
          trigger: "One partner writes a sensitive journal entry and sets it to response-gated.",
          steps: [
            "Partner A writes entry, sets visibility to 'visible after response'.",
            "Partner B sees that an entry exists but cannot read it.",
            "Partner B writes their own reflection in return.",
            "Both entries unlock simultaneously — neither read the other's first.",
          ],
          before: "One-sided emotional exposure with no structural guarantee of reciprocity.",
          after: "Reciprocity encoded at the protocol level — not relying on goodwill.",
        },
        {
          id: "UC-04",
          title: "Anticipatory Gift",
          who: "Partner wanting to mark a meaningful upcoming date",
          trigger: "Exam, anniversary, or difficult day approaching for the other partner.",
          steps: [
            "Create a voice-message gift, set to unlock on the morning of the event.",
            "Countdown becomes a small daily touchpoint in the days leading up.",
            "Gift unlocks at the scheduled time — sender gets no 'opened yet' signal.",
          ],
          before: "A text on the day — no anticipation, no buildup.",
          after: "The countdown itself is part of the gift.",
        },
        {
          id: "UC-05",
          title: "Offline Message Resilience",
          who: "Partner with unreliable connectivity",
          trigger: "Sending a message while entering a tunnel or low-signal area.",
          steps: [
            "Message queued in IndexedDB with client-generated temp ID.",
            "UI shows soft 'Queued' indicator — no silent failure, no generic error.",
            "On reconnect, message sends automatically with deduplication.",
          ],
          before: "Message fails silently or shows a generic error — partner has to retry manually.",
          after: "Seamless delivery on reconnect, no duplicate sends.",
        },
      ],
      workflow: [
        "Partner A creates account and sends invite to Partner B's email.",
        "Partner B accepts — relationship moves from pending → active, shared space unlocks.",
        "Both partners see the same Timezone Bridge, presence status, and mood check-in on the dashboard.",
        "Real-time events (messages, taps, calls) flow over WebSocket layer with optimistic UI updates.",
        "Calls connect peer-to-peer via WebRTC — content never transits a central server.",
        "Offline actions queue in IndexedDB, reconcile with server on reconnect with deduplication.",
        "Journal entries with response-gated visibility are locked at the data layer until reciprocity condition is met.",
        "Time Capsule mutual-unlock requires both partners to independently confirm before content is revealed.",
        "Habit streaks calculated by date-adjacency per local midnight — timezone-aware, not a shared cutoff.",
        "AI Story generation triggers at meaningful message-count and anniversary thresholds automatically.",
        "Relationship end archives history (read-only) — active connection stops, memories and messages preserved.",
      ],
      businessFlow: [
        "Two people agree to share a space → one sends invite, one accepts → dyad activated.",
        "Daily ambient layer: mood check-in, heartbeat taps, presence status — sub-conversational, no obligation.",
        "Synchronous layer: calls and Watch Together — highest richness, highest friction, used when both are available.",
        "Asynchronous layer: chat, journal, gifts, capsules — persistent, accumulates over time.",
        "Ritual layer: habit streaks and planner — system remembers and maintains rhythm so partners don't have to.",
        "Memory layer: timeline auto-curates shared history — raw material assembled into a legible story.",
        "Insight layer: AI Story generates narrative artifacts at milestones — relationship's own history handed back to them.",
      ],
      beforeVsAfter: [
        { aspect: "Timezone coordination", before: "Mental arithmetic every time, risk of waking partner", after: "One screen: dual clocks, heuristic, golden window" },
        { aspect: "Shared experience", before: "'Press play on 3' — always slightly off", after: "Join-gated sync with live position handoff" },
        { aspect: "Emotional state visibility", before: "Only if someone explicitly says something", after: "Daily mood check-in + ambient heartbeat tap" },
        { aspect: "Vulnerable disclosure", before: "One-sided, relies entirely on goodwill", after: "Response-gated journal — reciprocity at protocol level" },
        { aspect: "Relationship history", before: "Scattered across camera rolls and chat scrolls", after: "Purpose-built Memory Timeline, auto-curated AI Story" },
        { aspect: "Ritual maintenance", before: "Rituals lapse quietly under distance and fragmentation", after: "Habit streaks with streak logic and gentle reminders" },
        { aspect: "Audience anxiety", before: "Context collapse on any multi-audience platform", after: "Structurally absent — two-member data model, no third path" },
        { aspect: "Offline resilience", before: "Silent failure or generic error, manual retry", after: "IndexedDB queue, auto-send on reconnect, no duplicates" },
      ],
      screenshots: [
        { url: "/PairSpace/PairSpace1.png" },
        { url: "/PairSpace/PairSpace2.png" },
        { url: "/PairSpace/PairSpace3.png" },
        { url: "/PairSpace/PairSpace4.png" },
        { url: "/PairSpace/PairSpace6.png" },
        { url: "/PairSpace/PairSpace7.png" },
        { url: "/PairSpace/PairSpace8.png" },
        { url: "/PairSpace/PairSpace9.png" },
        { url: "/PairSpace/PairSpace10.png" },
        { url: "/PairSpace/PairSpace11.png" },
        { url: "/PairSpace/PairSpace12.png" },
      ],
      futureScope: [
        "Mobile app (React Native) with offline sync for low-connectivity environments.",
        "True generative AI Story using a language model rather than rule-based templating.",
        "Granular per-type notification preferences — different thresholds for every couple.",
        "Grace periods and streak protections for habit streaks — reduce guilt from honest misses.",
        "Time Travel UI — step backward through relationship state at any historical point.",
        "Expanded relationship types — best friends, family pairs — with non-romantic visual language.",
        "Multi-region high-availability deployment for national-scale reliability.",
        "Object store integration (MinIO) for long-horizon voice/video capsule storage.",
      ],
      limitations: [
        "WebRTC peer-to-peer calls require both clients to support the protocol — fallback for restrictive networks not yet implemented.",
        "Watch Together sync is best-effort on platforms that restrict programmatic seeking — not guaranteed flawless on every video source.",
        "AI Story is rule-based templating, not a generative language model — interpretive intelligence is limited to pattern matching.",
        "Awake/asleep heuristic in Timezone Bridge is probabilistic — a night-shift worker will be flagged incorrectly.",
        "Habit streak logic uses local midnight per user — edge cases at extreme timezone offsets require careful handling.",
        "Presence and mood signals that enable ambient intimacy are structurally the same data that could enable monitoring in an unhealthy relationship — mitigated by hidden status and symmetrical authority, but not fully resolved.",
        "Forgotten PIN on a locked memory has no clean recovery path — easy recovery weakens security, no recovery risks permanent content loss.",
      ],
      conclusion:
        "The central claim of PairSpace is narrower than it might first appear: relationships benefit from infrastructure — not novelty features bolted onto a chat app, but a coherent design philosophy where every feature traces back to a specific, named structural deficit of distance and a specific theoretical mechanism for addressing it. No single feature is remarkable on its own. A heartbeat button is a button. A mood emoji is an emoji. What makes PairSpace structurally different is the coherence across all of them — every one justified by the same underlying theory of what distance actually does to a relationship — which is the thing a general-purpose messaging app, social network, or video-calling tool cannot provide, because none of them were ever built around the dyad as the unit of design in the first place.",
    },
  },
  {
    slug: "youtube-backend",
    name: "YouTube Backend Clone",
    status: "shipped",
    oneLiner: "Production-grade Node.js + Express + MongoDB backend for a YouTube-like platform — built A-to-Z as a deep backend study.",
    problem: "Understanding how production backend systems are actually structured — auth, media uploads, aggregation pipelines, JWT rotation, and clean architecture — requires building one from scratch, not just reading about it.",
    stack: ["Node.js", "Express", "MongoDB", "Mongoose", "JWT", "bcrypt", "Cloudinary", "Multer", "cookie-parser", "CORS", "Axios", "Vite", "nodemon", "Prettier"],
    metrics: [
      { label: "API routes", value: "30+" },
      { label: "Controllers", value: "9" },
      { label: "Mongoose models", value: "7" },
      { label: "Auth strategy", value: "JWT + Refresh" },
    ],
    liveUrl: "https://youtube-backend-production.onrender.com/",
    pdfUrl: "/Yt_backend.pdf",
    featured: false,
    docs: {
      problemStatement:
        "Most backend tutorials teach isolated concepts — auth here, file upload there, aggregation somewhere else. This project was built to understand how all of it connects in a real, production-grade system: how JWT access + refresh token rotation works with cookies, how Multer + Cloudinary form a two-stage upload pipeline, how MongoDB aggregation pipelines compute channel stats and watch history, and how a clean Express architecture separates concerns across controllers, routes, middlewares, models, and utils.",
      existingProblems: [
        "Tutorials teach concepts in isolation — no single resource shows how auth, uploads, aggregation, and error handling connect in one codebase.",
        "JWT rotation (access + refresh token pair) is poorly explained in most resources — the cookie naming, DB storage, and rotation logic are all interdependent.",
        "File upload pipelines (Multer local temp → Cloudinary → cleanup) are rarely shown end-to-end with proper error handling.",
        "MongoDB aggregation pipelines for real use cases (subscriber counts, watch history with nested lookups) require hands-on implementation to understand.",
        "Production project hygiene — ESM modules, .env management, asyncHandler, ApiError/ApiResponse classes — is never covered in beginner tutorials.",
      ],
      whyThisProject:
        "This is a deliberate, A-to-Z backend study project built to production-grade standards. The goal was not to ship a product but to deeply understand every layer of a Node.js backend: how Express middleware chains work, how JWT tokens are issued and rotated, how Cloudinary integrates with Multer, and how MongoDB aggregation pipelines compute relational data without a relational database. The step-by-step folder structure (Youtube_Clone_Backend_STEPS/) documents the entire learning progression from HTTP basics to aggregation pipelines.",
      objectives: [
        "Implement JWT access + refresh token rotation with cookie-based storage and DB-side refresh token validation.",
        "Build a two-stage file upload pipeline: Multer local temp storage → Cloudinary upload → local cleanup.",
        "Write MongoDB aggregation pipelines for channel profile (subscriber count, isSubscribed) and watch history (nested video + owner lookup).",
        "Structure a production Express app with clean separation: controllers, routes, middlewares, models, utils.",
        "Implement consistent error handling via custom ApiError class and asyncHandler promise wrapper.",
        "Document every architectural decision and known issue for future reference.",
      ],
      solution:
        "The backend follows a clean layered architecture: client requests hit Express routes, pass through auth/multer middleware, reach controllers that call Mongoose models or aggregation pipelines, and return consistent JSON via ApiResponse. Auth uses a dual-token strategy — short-lived access tokens in cookies, long-lived refresh tokens stored in the DB and rotated on each refresh call. File uploads use Multer for local temp storage, then Cloudinary SDK for cloud upload, with local cleanup on both success and failure. MongoDB aggregation pipelines handle computed fields (subscriber counts, isSubscribed flags, nested watch history) that would require JOINs in a relational DB.",
      features: [
        "User Auth — register, login, logout with JWT access + refresh token pair stored in httpOnly cookies.",
        "Token Rotation — refresh endpoint verifies DB-stored refresh token, issues new pair, rotates DB record.",
        "Avatar & Cover Upload — Multer disk storage → Cloudinary upload → local temp cleanup, with error handling at each stage.",
        "Channel Profile Aggregation — MongoDB pipeline: subscriber count, subscribed-to count, isSubscribed flag for requesting user.",
        "Watch History Aggregation — nested $lookup: user → videos → video owner details, all in one pipeline.",
        "Account Management — change password, update account details, update avatar, update cover image.",
        "asyncHandler utility — Promise.resolve wrapper so every controller avoids try/catch boilerplate.",
        "ApiError class — extends Error with statusCode, structured errors array, stack trace capture.",
        "ApiResponse class — consistent envelope: statusCode, data, message, success flag.",
        "9 route modules — users, videos, comments, likes, playlists, subscriptions, tweets, dashboard, healthcheck.",
        "Controller skeletons — video CRUD, comments, likes, playlists, subscriptions, tweets, dashboard all scaffolded and ready to implement.",
        "CORS + cookie config — credentials: true, configurable origin via env, httpOnly + secure cookie flags.",
      ],
      userRoles: [
        { role: "Authenticated User", description: "JWT-verified via verifyJWT middleware. Access to all protected routes: profile, uploads, channel, watch history, subscriptions." },
        { role: "Public", description: "Register and login endpoints only. No access to protected routes without a valid access token." },
      ],
      workflow: [
        "Client sends POST /api/v1/users/register with multipart form-data (fields + avatar file).",
        "Multer middleware stores avatar to ./public/temp locally.",
        "registerUser controller validates fields, checks duplicate email/username.",
        "uploadoncloudinary() uploads temp file to Cloudinary, deletes local temp on success.",
        "User document created in MongoDB with Cloudinary URL stored as avatar field.",
        "Client sends POST /api/v1/users/login with username/email + password.",
        "loginUser validates password via bcrypt, generates access + refresh tokens.",
        "Refresh token saved to user.refreshtoken in DB. Both tokens set as httpOnly cookies.",
        "Protected routes: verifyJWT extracts token from cookie or Authorization header, verifies, loads user, sets req.user.",
        "Token expiry: client calls POST /api/v1/users/refresh-token with refresh token cookie.",
        "refreshAccesstoken verifies token, checks DB match, issues new pair, rotates DB record.",
        "GET /api/v1/users/c/:username runs aggregation pipeline: subscriber count, isSubscribed, channel fields.",
        "GET /api/v1/users/history runs nested aggregation: user watchHistory → video docs → owner details.",
      ],
      businessFlow: [
        "Request arrives → Express router matches path → middleware chain runs (CORS, JSON parse, cookie parse).",
        "Auth middleware (verifyJWT) extracts and verifies JWT → attaches req.user.",
        "Multer middleware (where needed) → stores file to temp → passes req.files to controller.",
        "Controller executes business logic → calls Mongoose model or aggregation pipeline.",
        "ApiResponse wraps result → consistent JSON envelope sent to client.",
        "ApiError thrown anywhere → caught by Express error handler → structured error response.",
        "asyncHandler wraps every controller → unhandled promise rejections forwarded to next().",
      ],
      beforeVsAfter: [
        { aspect: "Auth knowledge", before: "Knew JWT existed, didn't understand rotation or cookie storage", after: "Implemented full access + refresh rotation with DB-side validation" },
        { aspect: "File uploads", before: "Never built a multi-stage upload pipeline", after: "Multer → Cloudinary → cleanup with error handling at each stage" },
        { aspect: "MongoDB aggregation", before: "Only used basic find/findOne queries", after: "Built $lookup, $addFields, $project pipelines for real computed data" },
        { aspect: "Error handling", before: "try/catch in every function", after: "asyncHandler + ApiError class — zero boilerplate in controllers" },
        { aspect: "Project structure", before: "Everything in one file", after: "Clean separation: controllers / routes / middlewares / models / utils" },
        { aspect: "Known bugs", before: "Bugs were invisible", after: "Documented: cookie name mismatch, field name mismatch, router file misnaming" },
      ],
      futureScope: [
        "Complete all TODO controller methods: video CRUD, comments, likes, playlists, subscriptions, tweets, dashboard.",
        "Fix known mismatches: accesstoken vs accessToken cookie name, coverImage vs coverimage field name.",
        "Add pagination to video listing and comment endpoints using mongoose-aggregate-paginate-v2.",
        "Add frontend (React + Vite) to consume the API and complete the full-stack picture.",
        "Add rate limiting and helmet for production security hardening.",
        "Write unit tests for controllers and aggregation pipelines.",
      ],
      limitations: [
        "Most controllers (video, comments, likes, playlists, subscriptions, tweets, dashboard) are TODO skeletons — only user auth and profile are fully implemented.",
        "Cookie name mismatch: loginUser sets 'accesstoken' but verifyJWT reads 'accessToken' — breaks auth until fixed.",
        "Cover image field name mismatch: route uses upload.single('coverImage') but controller expects 'coverimage'.",
        "video.routes.js file contains user routes due to a naming error — routing confusion until corrected.",
        "No frontend — this is a backend-only project, tested via Postman/API client.",
        "Healthcheck controller is a TODO stub.",
      ],
      conclusion:
        "This project achieved its core goal: a deep, hands-on understanding of how a production Node.js backend is actually structured. Every architectural decision — dual-token auth, two-stage file upload, aggregation pipelines, consistent error handling — was implemented from scratch and documented with its reasoning and known issues. The TODO skeletons are intentional scope boundaries, not gaps: the auth, upload, and aggregation layers — the hardest and most educational parts — are fully implemented and production-grade.",
    },
  },
  {
    slug: "aidflow",
    name: "AidFlow AI",
    status: "active",
    oneLiner: "Unified autonomous infrastructure for transparent donations and disaster relief — AI verification, blockchain audit trails, programmable relief wallets, and multi-role governance in one platform.",
    problem: "Humanitarian aid systems process billions annually yet remain fragmented, opaque, and reactive — donations disappear into manual approval chains, beneficiary verification is trust-based, and financial misuse is discovered only after the damage is done.",
    stack: ["React", "Vite", "Tailwind CSS", "Node.js", "Express", "MongoDB", "Mongoose", "Redis", "BullMQ", "FastAPI", "Python", "JWT", "Ethereum", "Solidity", "Hardhat", "Web3.js", "Zod"],
    metrics: [
      { label: "User roles", value: "6" },
      { label: "Backend modules", value: "18" },
      { label: "AI agents", value: "4" },
      { label: "Queue workers", value: "7" },
    ],
    pdfUrl: "/AidFlow/AidFlow.pdf",
    featured: true,
    docs: {
      problemStatement:
        "Humanitarian aid organizations receive billions of dollars annually through governments, NGOs, charities, CSR initiatives, and disaster relief agencies. Despite these resources, millions of beneficiaries continue to experience delayed assistance, financial leakages, corruption, inefficient verification, and a complete lack of transparency regarding how donated funds are actually utilized. The issue is not the absence of goodwill or funding — the root cause lies in fragmented execution systems that rely on manual approvals, trust-based financial transfers, isolated databases, and retrospective audits. A donor contributes to a campaign and immediately loses visibility. An NGO receives funds with no enforceable spending controls. A beneficiary waits weeks for manual eligibility review. A government monitors nothing in real time. Fraud is discovered months after it occurs. No existing platform addresses the complete post-donation lifecycle — from donor contribution to final beneficiary utilization — with verifiable, programmable accountability.",
      existingProblems: [
        "Lack of Transparency: Donors rarely receive verifiable proof of how contributions are utilized. Most organizations provide annual reports or generalized campaign updates instead of transaction-level accountability.",
        "Delayed Aid Distribution: Traditional approval chains require multiple administrative layers before assistance reaches beneficiaries. During disasters, even minor delays significantly impact survival and recovery.",
        "Financial Misuse: Cash-based systems lack enforceable spending restrictions, allowing donated funds to be diverted toward unintended purposes. Misuse is frequently detected only after financial damage has occurred.",
        "Fragmented Information: Critical data is distributed across donation platforms, government databases, NGO records, disaster monitoring systems, banking infrastructure, and audit reports — preventing end-to-end visibility.",
        "Trust Crisis: Many donors discontinue contributions because they cannot independently verify organizational claims. Current trust models rely on reputation and marketing rather than objective evidence.",
        "No Programmable Financial Controls: Existing platforms have no mechanism to enforce that donated funds are spent only on food, medicine, or shelter — unrestricted cash reaches beneficiaries with no policy enforcement.",
        "Manual Beneficiary Verification: Eligibility assessment depends entirely on human reviewers, creating bottlenecks, inconsistency, and opportunities for duplicate or fraudulent claims.",
        "No Immutable Audit Trail: Traditional databases allow administrators to modify records silently. There is no cryptographic proof that a transaction occurred as reported.",
      ],
      whyThisProject:
        "Every existing solution addresses one isolated component of the humanitarian process. Traditional NGOs have outreach but limited transparency. Crowdfunding platforms enable fundraising but have no impact verification. Government relief systems operate at scale but with bureaucratic delays. Blockchain projects provide immutable records but lack operational workflow. AI solutions offer prediction and analytics but no financial execution. No existing approach combines governance, automation, verification, auditing, and programmable finance into one complete system. AidFlow AI was built to be that missing execution layer — transforming humanitarian intent into programmable, verifiable, and autonomous financial execution where accountability is an intrinsic property of the system rather than an optional organizational practice.",
      objectives: [
        "Establish transparent donation ecosystems where every contribution is traceable from donor to final utilization.",
        "Eliminate blind trust through evidence-based auditing — every important event creates an immutable blockchain-anchored record.",
        "Automate beneficiary verification using AI eligibility, fraud detection, and risk assessment agents.",
        "Prevent financial misuse through programmable relief wallets that enforce policy-driven spending restrictions.",
        "Enable immutable blockchain audit trails using Merkle Trees anchored to Ethereum smart contracts.",
        "Support governments through real-time oversight, policy management, and emergency disaster response workflows.",
        "Build dynamic trust scores based on measurable behavior rather than organizational reputation.",
        "Reduce fraud and duplicate claims through continuous AI monitoring across all platform activity.",
        "Simplify humanitarian governance through intelligent automation while keeping final authority with human stakeholders.",
      ],
      solution:
        "AidFlow AI introduces a unified humanitarian execution infrastructure built on six pillars: AI Decision Engine, Donation Management System, Disaster Relief Management, Blockchain Audit Infrastructure, Trust & Reputation Engine, and Rule-Based Financial Execution. The platform follows a seven-layer architecture — Presentation, API, Business Logic, AI, Background Processing, Blockchain, and Database — where each layer has a single responsibility while remaining loosely coupled. When a donation is made, it triggers a 10-step lifecycle: payment → audit record → BullMQ queue → AI risk evaluation → campaign update → beneficiary allocation → programmable wallet creation → merchant QR payment → Merkle Tree construction → Ethereum anchor. Beneficiary wallets enforce policy-driven spending restrictions (food, medicine, shelter only — no cash withdrawal, no luxury goods) validated at every merchant transaction. The blockchain layer stores only cryptographic Merkle Roots — never personal data — achieving immutable public verifiability at minimal gas cost. Three AI agents (Eligibility, Fraud Detection, Risk Assessment) feed a Decision Engine that outputs Approve / Reject / Manual Review / Escalate with full explainability logs.",
      features: [
        "Donor Module — Campaign discovery with filters (disaster type, NGO, location, urgency), secure donation flow with unique Donation ID + blockchain reference, full donation tracking through 8 lifecycle states (Created → Completed), public audit viewer with Merkle verification, NGO trust scores, and impact reports.",
        "NGO Module — Campaign lifecycle management (Draft → Archived), beneficiary onboarding and document verification, proof upload system (bills, invoices, geo-tagged photos, videos), AI validation of uploaded proofs (duplicate detection, metadata validation, forgery detection), trust score monitoring, and campaign analytics dashboard.",
        "Beneficiary Module — Structured registration with KYC, AI eligibility assessment, programmable digital relief wallet with QR payments, policy-enforced spending categories (food, medicine, shelter, education, hygiene), automatic wallet expiry with fund return, and full transaction history.",
        "Merchant Module — Business registration and category verification, QR code payment acceptance, real-time policy and wallet validation before every transaction, settlement processing with audit generation, blockchain anchoring per transaction, and fraud monitoring.",
        "Government Module — Policy creation and versioning (immutable after activation), disaster declaration with emergency workflow activation, national monitoring dashboard with geographic heatmaps, NGO verification and compliance oversight, fraud investigation workflows, and bulk report export (PDF, CSV, Excel, JSON).",
        "Administrator Module — Full user lifecycle management across all 6 roles, BullMQ queue monitoring (pending/running/failed jobs per worker), AI service health monitoring (response times, prediction accuracy, model versions), blockchain anchoring status and gas usage tracking, security center (failed logins, brute force, API abuse), and maintenance mode controls.",
        "AI Eligibility Engine — Multi-factor evaluation: household size, income, disability, disaster severity, employment status, duplicate detection, policy rules. Outputs: Eligible / Conditionally Eligible / Manual Review / Rejected with full explainability log.",
        "AI Fraud & Anomaly Agent — Continuous monitoring for duplicate beneficiaries, fake NGOs, duplicate documents, fake proof uploads, repeated claims, wallet abuse, merchant collusion, volume/time anomalies, beneficiary reuse, and cluster detection. Risk levels: Low / Medium / High / Critical.",
        "AI Risk Assessment Engine — Transaction risk scoring across NGO trust, campaign history, beneficiary risk, merchant behavior, geographic anomalies, and historical fraud. Feeds the Decision Engine for Approve / Reject / Escalate outcomes.",
        "AI Resource Planning Agent — Inventory + funds input, outputs distribution suggestions and optimal allocation. Confidence & Escalation Agent decides when AI is unsure and triggers human review with explainability logs.",
        "Geo-Fenced Merchant Execution — Merchants are location-locked and category-locked (food/medicine). Cannot initiate transactions without beneficiary presence, cannot exceed category limits, cannot split transactions, cannot transact outside geo-fence. Volume/time anomaly detection per merchant.",
        "Quadratic Relief Allocation — Need-weighted distribution algorithm considering family size, disability, children count, damage severity, and past aid received. Most vulnerable receive proportionally more — no political bias.",
        "Distributed Governance Model — No single actor controls the full pipeline. Donor provides intent only, NGO provides ground data, Government sets constraints, AI executes, Public audits. Emergency overrides require time limit + reason logging + post-fact audit.",
        "Zero-Trust Security Architecture — Every actor assumed potentially malicious. Defense-in-depth: financial fraud solved by programmable money, identity fraud by multi-source verification, insider abuse by separation of powers + immutable logs, AI hallucination by confidence thresholds + human escalation.",
        "Explainable AI (XAI) Layer — Every AI decision includes a human-readable 'WHY' explanation, confidence score, and contributing factors. Example: '₹5000 approved because: flood severity 8, family size 6, house destroyed.' Court-defensible and ethically auditable.",
        "Blockchain Audit Infrastructure — SHA-256 hashing of every audit event, Merkle Tree construction, Merkle Root anchored to Ethereum smart contract, public verification portal where anyone can verify any donation by ID without administrative access.",
        "Dynamic Trust Engine — Continuously calculated trust scores for NGOs, beneficiaries, merchants, and campaigns based on measurable behavior: campaign success, proof accuracy, fraud incidents, policy compliance, beneficiary feedback, and response time.",
        "Programmable Relief Wallets — Policy-governed wallets with category restrictions, QR payment support, automatic expiry, balance tracking, spending notifications, and blockchain verification reference per transaction.",
        "Queue-Based Background Processing — 7 BullMQ workers (Donation, AI, Fraud, Blockchain, Wallet Expiry, Notification, Recurring Donation) with Redis backing, automatic retry on failure, dead letter queue, and administrator alerts.",
        "Public Transparency Portal — Anyone can search by Donation ID, Campaign ID, Audit ID, or Blockchain Transaction to verify humanitarian transactions independently without requiring platform access.",
        "Notification System — Multi-priority (Low/Medium/High/Critical/Emergency) in-app and email notifications for every significant humanitarian event across all 6 roles.",
      ],
      userRoles: [
        { role: "Donor", description: "Contributes funds, browses verified campaigns, tracks donations through full lifecycle, views blockchain proof, accesses public audit timeline, and receives impact reports. Cannot approve campaigns, modify beneficiaries, or change policies." },
        { role: "NGO", description: "Creates and manages campaigns, onboards and verifies beneficiaries, distributes aid, uploads utilization proofs, monitors trust score, and views campaign analytics. Cannot change platform policies or access other NGO data." },
        { role: "Beneficiary", description: "Registers with KYC, undergoes AI eligibility assessment, receives programmable relief wallet, makes QR payments at approved merchants within policy-defined spending categories. Cannot create campaigns or modify wallet restrictions." },
        { role: "Merchant", description: "Registers with business verification, accepts humanitarian wallet QR payments, views settlements and transaction history. Cannot modify wallet rules, aid policies, or beneficiary records." },
        { role: "Government", description: "Creates and versions humanitarian policies, declares disasters to activate emergency workflows, monitors national campaigns and beneficiaries in real time, verifies NGOs, reviews fraud investigations, and exports compliance reports. Cannot edit blockchain records or alter audit logs." },
        { role: "Administrator", description: "Manages all users and roles, monitors BullMQ queues and workers, supervises AI services and blockchain anchoring, maintains audit integrity, manages security incidents, and controls platform configuration. Cannot modify blockchain history or manipulate trust calculations." },
      ],
      useCases: [
        {
          id: "UC-01",
          title: "End-to-End Donation Lifecycle",
          who: "Donor",
          trigger: "Donor selects a verified flood relief campaign and makes a contribution.",
          steps: [
            "Donor browses campaigns filtered by disaster type and NGO trust score.",
            "Donation initiated — payment gateway processes, Donation ID generated.",
            "Audit event created, BullMQ job queued for AI risk evaluation.",
            "AI Risk Agent evaluates transaction — Low Risk returned.",
            "Campaign updated, NGO receives fund allocation notification.",
            "NGO verifies beneficiaries, AI Eligibility Agent approves 47 of 50 applicants.",
            "Programmable wallets created for 47 beneficiaries with food + medicine restrictions.",
            "Beneficiaries make QR purchases at approved merchants — each transaction validated by Policy Engine.",
            "NGO uploads geo-tagged proof photos — AI validates metadata and location.",
            "Merkle Root anchored to Ethereum. Donor views blockchain verification on dashboard.",
          ],
          before: "Donor donates and loses all visibility. No proof of utilization ever received.",
          after: "Donor tracks every stage from contribution to final beneficiary purchase with blockchain proof.",
        },
        {
          id: "UC-02",
          title: "Disaster Emergency Response",
          who: "Government",
          trigger: "Cyclone declared affecting 3 coastal districts.",
          steps: [
            "Government declares disaster in AidFlow — emergency policy automatically activated.",
            "Affected areas imported, priority beneficiaries identified by AI eligibility scoring.",
            "NGOs assigned to districts, aid allocation computed by policy rules.",
            "Wallets funded within hours — no manual approval chain required.",
            "Merchant network activated in affected zones.",
            "Government dashboard shows real-time distribution progress with geographic heatmap.",
            "All transactions anchored to blockchain — full audit available to public.",
          ],
          before: "Multi-week bureaucratic approval chain before aid reaches affected families.",
          after: "Policy-driven automated distribution within hours of disaster declaration.",
        },
        {
          id: "UC-03",
          title: "Fraud Detection and Investigation",
          who: "AI Fraud Agent + Government",
          trigger: "Same beneficiary identity appears in 3 different campaigns across 2 NGOs.",
          steps: [
            "AI Fraud Agent flags duplicate identity — High Risk score generated.",
            "Audit event created, wallets frozen pending investigation.",
            "Government fraud dashboard surfaces the case with evidence trail.",
            "Manual investigation confirms fraudulent registration.",
            "Account permanently banned, trust scores of associated NGO reviewed.",
            "Public audit record updated — resolution visible to all stakeholders.",
          ],
          before: "Duplicate beneficiary collects aid from multiple campaigns undetected for months.",
          after: "Detected in real time before second wallet is funded.",
        },
        {
          id: "UC-04",
          title: "Merchant Payment Validation",
          who: "Beneficiary + Merchant",
          trigger: "Beneficiary attempts to purchase essential goods at an approved food store.",
          steps: [
            "Merchant generates invoice, QR code displayed.",
            "Beneficiary scans QR — wallet validation initiated.",
            "Policy Engine checks: merchant verified, category approved (food), wallet active, balance sufficient.",
            "Transaction approved in under 2 seconds.",
            "Audit event generated, blockchain anchor queued.",
            "Merchant receives settlement confirmation.",
          ],
          before: "Unrestricted cash — beneficiary could spend on anything, no accountability.",
          after: "Every purchase validated against policy in real time — only approved categories accepted.",
        },
        {
          id: "UC-05",
          title: "Public Audit Verification",
          who: "Independent Journalist / Regulatory Inspector",
          trigger: "Investigating whether a specific campaign's funds were actually distributed.",
          steps: [
            "Inspector opens Public Transparency Portal — no login required.",
            "Searches by Campaign ID — full audit timeline displayed.",
            "Each event shows actor, action, timestamp, and hash.",
            "Merkle proof verified against Ethereum transaction hash.",
            "Blockchain explorer link confirms anchor is immutable and unmodified.",
          ],
          before: "No independent verification possible — organization's word is the only evidence.",
          after: "Cryptographic proof of every transaction available to anyone, anywhere, without platform access.",
        },
      ],
      workflow: [
        "User authenticates → JWT issued → role-specific permissions loaded.",
        "Donor makes donation → payment gateway → Donation document created in MongoDB.",
        "Audit event generated → SHA-256 hash computed → stored in Audit collection.",
        "BullMQ Donation Worker picks up job → AI Worker triggered.",
        "FastAPI AI service evaluates: Eligibility Agent + Fraud Agent + Risk Agent → Decision Engine.",
        "Decision returned → campaign updated → NGO notified.",
        "NGO verifies beneficiaries → AI Eligibility Agent runs → approved beneficiaries get wallets.",
        "Wallet Worker creates programmable wallet → policy restrictions applied → beneficiary notified.",
        "Beneficiary scans merchant QR → Policy Engine validates merchant + category + balance → transaction approved.",
        "Settlement generated → Audit event created → Blockchain Worker queues Merkle anchor.",
        "Blockchain Worker batches audit hashes → builds Merkle Tree → anchors root to Ethereum smart contract.",
        "Transaction hash stored in MongoDB → Public Verification Portal updated.",
        "Notification Worker delivers role-appropriate alerts across all stakeholders.",
        "Trust Engine recalculates scores based on completed events → dashboards refreshed.",
      ],
      businessFlow: [
        "Donor contributes → campaign receives funds → NGO executes distribution.",
        "AI continuously validates every verification, transaction, and proof upload.",
        "Programmable wallets enforce spending policy — aid converts to essential goods only.",
        "Every action generates an audit event → Merkle Tree → blockchain anchor → public proof.",
        "Government monitors national operations in real time — intervenes only when policy requires.",
        "Trust scores evolve continuously — honest behavior rewarded, fraud penalized automatically.",
        "Emergency declared → policy activates → wallets funded → distribution begins within hours.",
        "Public portal provides independent verification without requiring platform access.",
      ],
      beforeVsAfter: [
        { aspect: "Donor visibility", before: "Donate and lose all visibility immediately", after: "Track every stage from contribution to final purchase with blockchain proof" },
        { aspect: "Beneficiary verification", before: "Manual review — weeks of delay, inconsistent outcomes", after: "AI eligibility + fraud + risk agents — minutes, consistent, explainable" },
        { aspect: "Financial controls", before: "Unrestricted cash — no enforceable spending policy", after: "Programmable wallets — policy-enforced categories, no cash withdrawal" },
        { aspect: "Fraud detection", before: "Discovered months after damage via retrospective audit", after: "Real-time AI detection before second wallet is funded" },
        { aspect: "Audit trail", before: "Database records modifiable by administrators — no tamper proof", after: "Merkle-anchored blockchain proof — cryptographically immutable" },
        { aspect: "Disaster response", before: "Multi-week bureaucratic approval chain", after: "Policy-driven automated distribution within hours of declaration" },
        { aspect: "Public trust", before: "Reputation-based — organizational claims unverifiable", after: "Evidence-based — cryptographic proof available to anyone" },
        { aspect: "NGO accountability", before: "Annual reports, no transaction-level proof", after: "Continuous AI-validated proof uploads, dynamic trust score" },
      ],
      futureScope: [
        "Disaster Anticipation Engine — AI trained on weather APIs, climate models, and historical disaster data to predict and pre-position aid BEFORE disaster occurs. Example: flood probability 80% in Ward-5 → preload wallets with emergency credits.",
        "Zero-Knowledge Proofs (ZKP) — Privacy-preserving beneficiary verification that proves eligibility without revealing name, Aadhaar, or address. Critical for refugee identity safety and global deployment.",
        "Stablecoin Settlement — Replace fiat wallet system with on-chain stablecoin transfers for instant, borderless humanitarian payments with automatic FX handling and country-level compliance rules.",
        "DAO-Governed Emergency Rules — Multi-stakeholder governance (Govt + NGOs + Donor reps + Disaster experts) that approves global rules, defines thresholds, and audits AI decisions democratically.",
        "Digital Twin of Disaster Relief — Simulation environment to run 'what-if' scenarios, test rules before real execution, and predict bottlenecks. Example: 'If flood hits 3 wards simultaneously, will funds last?'",
        "Reputation Slashing & Incentive Mechanism — Game-theoretic design: NGOs with high trust score get faster fund release and higher allocation priority. Fraud detected → reputation slashed + wallet frozen + public warning.",
        "Offline-First Mobile App — React Native app with IndexedDB queue for beneficiary wallet usage in low-connectivity disaster zones.",
        "Aadhaar / DigiLocker Integration — Government identity API integration for instant, verified beneficiary onboarding in India.",
        "Cross-Border & Multi-Currency Aid Engine — Stablecoin abstraction layer with automatic FX handling and sanctions/compliance rules by country. Makes AidFlow UN-scale.",
        "Carbon & Sustainability Accounting — Track carbon saved vs physical aid logistics, optimized routing impact. Appeals to EU/UN/global ESG funds.",
        "Open Protocol — AidFlow as an open standard with APIs for governments and SDKs for NGOs, auditable by anyone. Like HTTP for disaster aid.",
        "Federated Learning — Train fraud detection models across multiple NGO datasets without centralizing sensitive beneficiary data.",
      ],
      limitations: [
        "Under active development — system design and architecture are complete; Phase 1 (Backend Core: Policy Engine, Wallet Engine, Workflow Engine) is in progress.",
        "Blockchain confirmation introduces unavoidable latency — Merkle anchoring is asynchronous and depends on Ethereum network conditions.",
        "AI agents currently use rule-based heuristics — ML model training requires real-world disaster data not yet available at this stage.",
        "Government integrations (Aadhaar, DigiLocker, disaster APIs, weather APIs) depend on external regulatory approvals not yet obtained.",
        "Internet connectivity required for real-time wallet validation — offline payment fallback planned but not yet implemented.",
        "Geo-fencing accuracy depends on GPS availability — low-signal disaster zones may require fallback verification mechanisms.",
        "No mobile app yet — current implementation is web-only; React Native app is on the roadmap for Phase 2.",
        "Quadratic allocation algorithm requires verified household data — initial deployment uses simplified need-scoring until government data APIs are integrated.",
      ],
      conclusion:
        "AidFlow AI is not a donation platform. It is a policy-governed, AI-assisted, security-first execution infrastructure designed for chaos-heavy environments like disasters. The core philosophy is simple: trust is enforced, not requested. Rules are executable. AI is bounded and explainable. Money is programmable. Power is distributed. Audit is inevitable. Intent becomes rules, rules become execution, execution produces proof — automatically. The system assumes every actor can be malicious and is designed fail-safe, not fail-open. No single actor controls the full pipeline: donor provides intent, NGO provides ground data, government sets constraints, AI executes within those constraints, and the public audits everything. By combining programmable financial controls, multi-agent AI, distributed governance, and blockchain-anchored transparency, AidFlow AI transforms humanitarian accountability from an organizational promise into a mathematical guarantee.",
    },
  },
  {
    slug: "project-5",
    name: "[Project Five]",
    status: "shipped",
    oneLiner: "[One-line description — what it does, for whom.]",
    problem: "[Constraint or problem that made this worth building.]",
    stack: ["[Stack A]"],
    metrics: [{ label: "[Metric A]", value: "[Value]" }],
    liveUrl: "#",
    featured: false,
  },
  {
    slug: "project-6",
    name: "[Project Six]",
    status: "archived",
    oneLiner: "[One-line description — what it does, for whom.]",
    problem: "[Constraint or problem that made this worth building.]",
    stack: ["[Stack A]", "[Stack B]"],
    metrics: [{ label: "[Metric A]", value: "[Value]" }],
    github: "#",
    featured: false,
  },
];
