export const siteConfig = {
  name: "Parth",
  role: "AI / Infrastructure Systems Engineer",
  tagline: "Builds AI systems for critical infrastructure that have to be right, not just fast.",
  description:
    "Parth designs and ships production-grade AI systems for infrastructure-critical domains — currently building RailMind, an AI-powered railway infrastructure management platform.",
  url: "https://example.com",
  email: "prajapatiparth01.ab@gmail.com",
  phone: "[+91 XXXXX XXXXX]",
  location: "India",
  bookingUrl: "https://cal.com/parth-prajapati-lgfu8j",
  social: {
    github: "https://github.com/Ambivert01",
    linkedin: "https://www.linkedin.com/in/parthprajapati01",
    twitter: "https://twitter.com/yourhandle",
    medium: "https://medium.com/@yourhandle",
    devto: "https://dev.to/yourhandle",
    youtube: "https://youtube.com/@yourhandle",
    instagram: "https://instagram.com/yourhandle",
    behance: "https://behance.net/yourhandle",
    dribbble: "https://dribbble.com/yourhandle",
  },
  resumeUrl: "/resume.pdf",
  availability: "Open to select opportunities",
};
