// Maps project stack tech names → skill group.
// Version suffixes stripped automatically: "React 18" → "React", "Node.js 20" → "Node.js"
// Excluded intentionally: dev utilities (nodemon, bcrypt, CORS, cookie-parser, Sharp, Prettier, Axios, node-cron)

export const skillCategoryMap: Record<string, string> = {

  // ─── Languages ───────────────────────────────────────────────────────────────
  JavaScript: "Languages",
  TypeScript: "Languages",
  Python: "Languages",
  "C++": "Languages",
  C: "Languages",
  "C#": "Languages",
  SQL: "Languages",
  HTML: "Languages",
  CSS: "Languages",
  Go: "Languages",
  Rust: "Languages",
  Java: "Languages",
  Kotlin: "Languages",
  Swift: "Languages",
  Ruby: "Languages",
  PHP: "Languages",
  Scala: "Languages",
  Dart: "Languages",
  Bash: "Languages",
  Shell: "Languages",
  R: "Languages",
  SASS: "Languages",
  SCSS: "Languages",
  GraphQL: "Languages",

  // ─── Frontend ────────────────────────────────────────────────────────────────
  React: "Frontend",
  "Next.js": "Frontend",
  "Tailwind CSS": "Frontend",
  Vite: "Frontend",
  "Framer Motion": "Frontend",
  "Mapbox GL": "Frontend",
  "Vue.js": "Frontend",
  "Nuxt.js": "Frontend",
  Nuxt: "Frontend",
  Angular: "Frontend",
  Svelte: "Frontend",
  SvelteKit: "Frontend",
  Astro: "Frontend",
  Remix: "Frontend",
  Gatsby: "Frontend",
  Redux: "Frontend",
  Zustand: "Frontend",
  Jotai: "Frontend",
  Recoil: "Frontend",
  "React Query": "Frontend",
  "TanStack Query": "Frontend",
  "TanStack Router": "Frontend",
  "React Router": "Frontend",
  "Three.js": "Frontend",
  "React Three Fiber": "Frontend",
  "D3.js": "Frontend",
  "Chart.js": "Frontend",
  Recharts: "Frontend",
  "Shadcn UI": "Frontend",
  "Radix UI": "Frontend",
  "Material UI": "Frontend",
  "Ant Design": "Frontend",
  "Chakra UI": "Frontend",
  "Headless UI": "Frontend",
  "Styled Components": "Frontend",
  "CSS Modules": "Frontend",
  Storybook: "Frontend",
  Webpack: "Frontend",
  Rollup: "Frontend",
  esbuild: "Frontend",
  "Leaflet.js": "Frontend",
  "Deck.gl": "Frontend",
  GSAP: "Frontend",
  "Motion One": "Frontend",

  // ─── Backend ─────────────────────────────────────────────────────────────────
  "Node.js": "Backend",
  Express: "Backend",
  NestJS: "Backend",
  "REST APIs": "Backend",
  WebSockets: "Backend",
  WebRTC: "Backend",
  "Socket.IO": "Backend",
  Prisma: "Backend",
  JWT: "Backend",
  Multer: "Backend",
  FastAPI: "Backend",
  Django: "Backend",
  Flask: "Backend",
  "Spring Boot": "Backend",
  "Ruby on Rails": "Backend",
  Laravel: "Backend",
  Hono: "Backend",
  Elysia: "Backend",
  Fastify: "Backend",
  Koa: "Backend",
  tRPC: "Backend",
  "Apollo Server": "Backend",
  "GraphQL Yoga": "Backend",
  Hasura: "Backend",
  Drizzle: "Backend",
  "Drizzle ORM": "Backend",
  Sequelize: "Backend",
  TypeORM: "Backend",
  "Passport.js": "Backend",
  OAuth: "Backend",
  "OAuth 2.0": "Backend",
  "NextAuth.js": "Backend",
  "Auth.js": "Backend",
  Clerk: "Backend",
  BullMQ: "Backend",
  "Bull Queue": "Backend",
  Agenda: "Backend",
  gRPC: "Backend",
  "Protocol Buffers": "Backend",
  "Server-Sent Events": "Backend",
  SSE: "Backend",
  Zod: "Backend",

  // ─── Databases ───────────────────────────────────────────────────────────────
  MongoDB: "Databases",
  Mongoose: "Databases",
  PostgreSQL: "Databases",
  MySQL: "Databases",
  Redis: "Databases",
  Neo4j: "Databases",
  SQLite: "Databases",
  MariaDB: "Databases",
  CockroachDB: "Databases",
  PlanetScale: "Databases",
  Supabase: "Databases",
  Firebase: "Databases",
  Firestore: "Databases",
  DynamoDB: "Databases",
  Cassandra: "Databases",
  Elasticsearch: "Databases",
  "Apache Kafka": "Databases",
  RabbitMQ: "Databases",
  Neon: "Databases",
  Turso: "Databases",
  libSQL: "Databases",
  Upstash: "Databases",
  Convex: "Databases",
  PGVector: "Databases",
  Pinecone: "Databases",
  Weaviate: "Databases",
  Chroma: "Databases",
  Milvus: "Databases",

  // ─── AI & Data ───────────────────────────────────────────────────────────────
  "LLM agent design": "AI & Data",
  "RAG systems": "AI & Data",
  LangGraph: "AI & Data",
  Qdrant: "AI & Data",
  "GPT-4o-mini": "AI & Data",
  "GPT-4o": "AI & Data",
  "GPT-4": "AI & Data",
  "GPT-3.5": "AI & Data",
  "Claude 3": "AI & Data",
  "Claude 3.5": "AI & Data",
  "Claude 3.7": "AI & Data",
  Gemini: "AI & Data",
  "Gemini Pro": "AI & Data",
  "Llama 3": "AI & Data",
  Mistral: "AI & Data",
  Ollama: "AI & Data",
  LangChain: "AI & Data",
  LlamaIndex: "AI & Data",
  "OpenAI SDK": "AI & Data",
  "Anthropic SDK": "AI & Data",
  "Hugging Face": "AI & Data",
  "Transformers.js": "AI & Data",
  TensorFlow: "AI & Data",
  PyTorch: "AI & Data",
  "scikit-learn": "AI & Data",
  Pandas: "AI & Data",
  NumPy: "AI & Data",
  Jupyter: "AI & Data",
  "Vercel AI SDK": "AI & Data",
  "AI SDK": "AI & Data",
  CrewAI: "AI & Data",
  "Crew AI": "AI & Data",
  AutoGen: "AI & Data",
  "Semantic Kernel": "AI & Data",
  "Prompt Engineering": "AI & Data",
  "Fine-tuning": "AI & Data",
  "Vector Search": "AI & Data",
  Embeddings: "AI & Data",

  // ─── DevOps ──────────────────────────────────────────────────────────────────
  Docker: "DevOps",
  Git: "DevOps",
  Linux: "DevOps",
  "CI/CD": "DevOps",
  "GitHub Actions": "DevOps",
  Turborepo: "DevOps",
  Kubernetes: "DevOps",
  "Docker Compose": "DevOps",
  Terraform: "DevOps",
  Ansible: "DevOps",
  "GitLab CI": "DevOps",
  CircleCI: "DevOps",
  Jenkins: "DevOps",
  Nginx: "DevOps",
  Caddy: "DevOps",
  PM2: "DevOps",
  Prometheus: "DevOps",
  Grafana: "DevOps",
  Nx: "DevOps",
  Lerna: "DevOps",
  pnpm: "DevOps",
  Bun: "DevOps",
  Deno: "DevOps",
  MinIO: "DevOps",

  // ─── Cloud ───────────────────────────────────────────────────────────────────
  Vercel: "Cloud",
  Render: "Cloud",
  AWS: "Cloud",
  "AWS Lambda": "Cloud",
  "AWS S3": "Cloud",
  "AWS EC2": "Cloud",
  "AWS RDS": "Cloud",
  "AWS ECS": "Cloud",
  "AWS CloudFront": "Cloud",
  GCP: "Cloud",
  "Google Cloud": "Cloud",
  Azure: "Cloud",
  Netlify: "Cloud",
  Railway: "Cloud",
  Fly: "Cloud",
  "Fly.io": "Cloud",
  "Cloudflare Workers": "Cloud",
  "Cloudflare Pages": "Cloud",
  "Cloudflare R2": "Cloud",

  // ─── Mobile ──────────────────────────────────────────────────────────────────
  "React Native": "Mobile",
  Expo: "Mobile",
  Flutter: "Mobile",

  // ─── Testing ─────────────────────────────────────────────────────────────────
  Jest: "Testing",
  Vitest: "Testing",
  Playwright: "Testing",
  Cypress: "Testing",
  Supertest: "Testing",
  "Testing Library": "Testing",
  "React Testing Library": "Testing",
  Mocha: "Testing",
  Chai: "Testing",
  k6: "Testing",

  // ─── Third-Party & Services ──────────────────────────────────────────────────
  Stripe: "Third-Party & Services",
  Cloudinary: "Third-Party & Services",
  Resend: "Third-Party & Services",
  Sentry: "Third-Party & Services",
  Razorpay: "Third-Party & Services",
  Nodemailer: "Third-Party & Services",
  Twilio: "Third-Party & Services",
  SendGrid: "Third-Party & Services",
  Pusher: "Third-Party & Services",
  Liveblocks: "Third-Party & Services",
  Ably: "Third-Party & Services",
  Algolia: "Third-Party & Services",
  Typesense: "Third-Party & Services",
  MeiliSearch: "Third-Party & Services",
  "Google Maps": "Third-Party & Services",
  "Google Analytics": "Third-Party & Services",
  Mixpanel: "Third-Party & Services",
  PostHog: "Third-Party & Services",
  Segment: "Third-Party & Services",
  Intercom: "Third-Party & Services",
  Crisp: "Third-Party & Services",
  "Sanity CMS": "Third-Party & Services",
  Contentful: "Third-Party & Services",
  Strapi: "Third-Party & Services",
  PayloadCMS: "Third-Party & Services",
  "AWS SES": "Third-Party & Services",
  "AWS SNS": "Third-Party & Services",
  "AWS SQS": "Third-Party & Services",
};
